# Site settings
title: Gustavo Mendonca's Github Page
name: Gustavo Mendonca
email: gustavogmend@gmail.com
description: >
    A simple Github Blog page.
baseurl: "https://gmendonca.github.io" # the subpath of your site, e.g. /blog
url: "https://gmendonca.github.io" # the base hostname & protocol for your site
twitter_username: gustavogmend # your Twitter username
github_username: gmendonca # your Github username

skillstree: true # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
